export const posts = [
  {
    username: "chomi_b",
    description:
      "📍 Commercial space available in Cubao, Quezon City — located just a 2-minute walk from the MRT station and beside a 24/7 convenience store. Ideal for a small café, mini mart, or printing shop. High foot traffic especially during rush hour and weekends. Rent is negotiable. DM for inquiries!",
    images_url: [require("../assets/images/post-1.jpg")],
    comment_count: 120,
    heart_count: 985,
    hasBookmarked: true,
    hasHearted: true,
    createdAt: "2025-06-27T14:22:00Z",
    price: null,
    address: "Aurora Blvd., Cubao, Quezon City",
  },
  {
    username: "mikaella23",
    description:
      "📦 Ground floor retail unit for lease at BGC High Street! 28 sqm of open layout space, right across a tech office hub and beside an established café. Best for boutique clothing, beauty, or quick-serve food. Biznest Score: 91. Available starting July. PM for rates and schedule of viewing.",
    images_url: [require("../assets/images/post-2.jpg")],
    comment_count: 87,
    heart_count: 1340,
    hasBookmarked: false,
    hasHearted: false,
    createdAt: "2025-06-25T10:15:00Z",
    price: null,
    address: "Bonifacio High Street, Taguig City",
  },
  {
    username: "juan_delo",
    description:
      "Sari-sari store front with attached stockroom for rent in Tondo. Family neighborhood, stable daily traffic, and no direct competition on the block. Perfect for someone looking to start small. Electricity and water available. 6-month minimum term.",
    images_url: [require("../assets/images/post-3.jpg")],
    comment_count: 41,
    heart_count: 300,
    hasBookmarked: false,
    hasHearted: true,
    createdAt: "2025-06-24T08:45:00Z",
    price: "₱4,500/month",
    address: "Velasquez St., Tondo, Manila",
  },
  {
    username: "trisha.codes",
    description:
      "📌 Katipunan Avenue — Commercial space available near Ateneo and UP. This is a corner unit with glass frontage, perfect for milk tea, laundromat, or gadget repair services. Constant flow of students and working professionals. Biznest score: 87. Send me a message for rent details!",
    images_url: [require("../assets/images/post-4.jpg")],
    comment_count: 112,
    heart_count: 4500,
    hasBookmarked: true,
    hasHearted: true,
    createdAt: "2025-06-23T17:05:00Z",
    price: "₱18,000/month",
    address: "Katipunan Ave., Quezon City",
  },
  {
    username: "vinsdailydose",
    description:
      "🍲 12 sqm stall for rent near UST. Location has proven foot traffic especially during lunch and dinner hours. Popular among students. Ideal for quick meals, rice bowls, milk tea, or frozen desserts. DM for pricing.",
    images_url: [require("../assets/images/post-5.jpg")],
    comment_count: 19,
    heart_count: 240,
    hasBookmarked: false,
    hasHearted: false,
    createdAt: "2025-06-22T11:30:00Z",
    price: null,
    address: "España Blvd., Sampaloc, Manila",
  },
  {
    username: "kyle.cam",
    description:
      "Studio for lease in Makati Poblacion — raw industrial space with high ceilings, ideal for creatives: photography, fashion, art, or even a private tattoo studio. Can be fitted based on your needs. Located inside a quiet compound with 24/7 access. Viewing available weekdays.",
    images_url: [require("../assets/images/post-6.jpg")],
    comment_count: 78,
    heart_count: 1100,
    hasBookmarked: true,
    hasHearted: true,
    createdAt: "2025-06-20T13:55:00Z",
    price: "₱22,000/month",
    address: "Don Pedro St., Poblacion, Makati City",
  },
  {
    username: "pinoynomad",
    description:
      "Caloocan warehouse unit for lease — 50 sqm storage with driveway access. Great for logistics, distribution, or e-commerce stock keeping. Close to major roads and transport hubs. Available for immediate occupancy. Monthly rent starts at ₱15,000.",
    images_url: [require("../assets/images/post-7.jpg")],
    comment_count: 54,
    heart_count: 870,
    hasBookmarked: false,
    hasHearted: true,
    createdAt: "2025-06-18T09:10:00Z",
    price: "₱15,000/month",
    address: "1st Ave., Grace Park, Caloocan City",
  },
  {
    username: "anne.m",
    description:
      "Shared coworking and mini event space in Ortigas — rent per seat or per hour available. Equipped with WiFi, aircon, whiteboard, coffee machine. Ideal for freelancers, students, and small workshops. Walk-in friendly. Biznest Score: 80.",
    images_url: [require("../assets/images/post-8.jpg")],
    comment_count: 66,
    heart_count: 1320,
    hasBookmarked: true,
    hasHearted: false,
    createdAt: "2025-06-15T16:20:00Z",
    price: "₱150/hour",
    address: "Emerald Ave., Ortigas Center, Pasig City",
  },
  {
    username: "thechefmike",
    description:
      "Fully equipped ghost kitchen available in Malate. 20 sqm kitchen area with stainless fixtures, range hood, and basic prep tables. Perfect for food delivery startups. Just plug in and start cooking. Contact for kitchen rates and usage terms. Limited slots only!",
    images_url: [require("../assets/images/post-9.jpg")],
    comment_count: 101,
    heart_count: 2230,
    hasBookmarked: false,
    hasHearted: true,
    createdAt: "2025-06-13T22:40:00Z",
    price: "₱12,000/month",
    address: "San Andres St., Malate, Manila",
  },
  {
    username: "nina_art",
    description:
      "Charming street-level space for lease in San Juan. Previously used as an art gallery. Quiet area, artistic vibe, and welcoming neighborhood. Good for cafés, craft shops, or studios. You’ll love the natural light all day. DM for schedule and walkthrough!",
    images_url: [require("../assets/images/post-10.jpg")],
    comment_count: 89,
    heart_count: 3150,
    hasBookmarked: true,
    hasHearted: true,
    createdAt: "2025-06-10T07:00:00Z",
    price: null,
    address: "N. Domingo St., San Juan City",
  },
];
