const icons = {
  icon: require("../assets/icons/icon.png"),
  home: require("../assets/icons/home-fill.png"),
  rent: require("../assets/icons/rent-fill.png"),
  locate: require("../assets/icons/locate.png"),
  profile: require("../assets/icons/user-fill.png"),
  filter: require("../assets/icons/filter.png"),
  addition: require("../assets/icons/addition.png"),
  search: require("../assets/icons/search.png"),
  more: require("../assets/icons/more.png"),
  bookmark: require("../assets/icons/bookmark.png"),
  heart: require("../assets/icons/heart.png"),
  comment: require("../assets/icons/comment.png"),
  pin: require("../assets/icons/pin.png"),
  peso: require("../assets/icons/peso.png"),
  next: require("../assets/icons/next.png"),
  down: require("../assets/icons/down.png"),
  x: require("../assets/icons/x.png"),
  evaluate: require("../assets/icons/evaluate.png"),
  send: require("../assets/icons/send.png"),
  cash: require("../assets/icons/cash.png"),
  camera: require("../assets/icons/camera.png"),
  arrowUp: require("../assets/icons/arrowUp.png"),
  "heart-fill": require("../assets/icons/heart-fill.png"),
  "pin-fill": require("../assets/icons/pin-fill.png"),
  "arrowUp-fill": require("../assets/icons/arrowUp-fill.png"),
  "bookmark-fill": require("../assets/icons/bookmark-fill.png"),
};

export default icons;
